{
 "title": "Ondat_Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(ondat_filesystem_avail_bytes, pvc_namespace)"
    }
   },
   {
    "name": "pvc",
    "label": "pvc",
    "query": {
     "query": "label_values(ondat_filesystem_avail_bytes{pvc_namespace =~ \"$namespace\"}, pvc)"
    }
   }
  ]
 },
 "panels": [
  { "title": "pvc-list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim,namespace) + sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=~\"(Lost)\"}) by (persistentvolumeclaim,namespace)"
    },
    {
     "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"} * 100)"
    }
   ]
  },
  { "title": "volume-metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "PVC Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ondat_disk_read_bytes_total{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}[$__rate_interval])",
     "legendFormat": "{{pvc}} reads"
    },
    {
     "expr": "rate(ondat_disk_written_bytes_total{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}[$__rate_interval])\n",
     "legendFormat": "{{pvc}} writes"
    }
   ]
  },
  {
   "title": "PVC R/W time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ondat_disk_read_time_seconds_total{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}[$__rate_interval])/rate(ondat_disk_reads_completed_total{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}[$__rate_interval])",
     "legendFormat": "{{pvc}} reads"
    },
    {
     "expr": "rate(ondat_disk_write_time_seconds_total{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}[$__rate_interval])/rate(ondat_disk_writes_completed_total{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}[$__rate_interval])",
     "legendFormat": "{{pvc}} write"
    }
   ]
  },
  {
   "title": "Time spent doing I/O",
   "type": "timeseries",
   "description": "%util",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(ondat_disk_io_time_seconds_total{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}[$__rate_interval])",
     "legendFormat": "{{pvc}}"
    }
   ]
  },
  {
   "title": "PVC free capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ondat_filesystem_avail_bytes{pvc != \"\",pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}",
     "legendFormat": "{{pvc}}"
    }
   ]
  },
  {
   "title": "Instant Queue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "irate(ondat_disk_io_now{pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}[$__rate_interval])\n",
     "legendFormat": "{{pvc}}"
    }
   ]
  },
  {
   "title": "PVC current free capacity",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ondat_filesystem_avail_bytes{pvc != \"\",pvc_namespace=~\"$namespace\", pvc=~\"$pvc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "api-manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Mutate requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{code = \"200\",webhook=\"/mutate-pods\"}[$__rate_interval]))",
     "legendFormat": "Success mutate-pods"
    },
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{code = \"200\",webhook=\"/mutate-pvcs\"}[$__rate_interval]))",
     "legendFormat": "Success mutate-pvcs"
    },
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{code = \"500\",webhook=\"/mutate-pods\"}[$__rate_interval]))",
     "legendFormat": "Failed mutate-pods"
    },
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{code != \"200\",webhook=\"/mutate-pvcs\"}[$__rate_interval]))",
     "legendFormat": "Failed mutate-pvcs"
    }
   ]
  },
  {
   "title": "Mutation requests in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_in_flight{webhook=\"/mutate-pods\"})",
     "legendFormat": "Mutate pods"
    },
    {
     "expr": "sum(controller_runtime_webhook_requests_in_flight{webhook=\"/mutate-pvcs\"})",
     "legendFormat": "Mutate PVCs"
    }
   ]
  }
 ]
}