apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-encrypted
  labels:
    storageos.com/encryption: "true"
spec:
  storageClassName: storageos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
