apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rwx
  labels:
      storageos.com/replicas: "1"
spec:
  storageClassName: storageos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
