apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-replicated
  labels:
      storageos.com/replicas: "1"
spec:
  storageClassName: storageos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
