apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ondat-failure-mode-soft
provisioner: csi.storageos.com
allowVolumeExpansion: true
parameters:
  storageos.com/replicas: "2"                           # Create 2 replica volumes.
  storageos.com/failure-mode: "soft"                    # Set failure mode to "soft".
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/secret-name: storageos-api
  csi.storage.k8s.io/secret-namespace: storageos