apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
          subPath: html
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: pvc-rwx
