apiVersion: v1
kind: Pod
metadata:
  name: pod-rwx
spec:
  containers:
    - name: debian
      image: debian:11-slim
      command: ["/bin/sleep"]
      args: [ "infinity" ]
      volumeMounts:
        - mountPath: /mnt/v1
          name: v1
        - mountPath: /mnt/v2
          name: v2
        - mountPath: /mnt/v3
          name: v3
  volumes:
    - name: v1
      persistentVolumeClaim:
        claimName: pvc-rwx1
    - name: v2
      persistentVolumeClaim:
        claimName: pvc-rwx2
    - name: v3
      persistentVolumeClaim:
        claimName: pvc-rwx3
