apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-topology-aware-placement
  labels:
      storageos.com/topology-aware: "true"
      storageos.com/replicas: "1"
spec:
  storageClassName: storageos-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
