apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-spot
  labels:
      storageos.com/replicas: "1"
      storageos.com/spot-instances: "stable"
spec:
  storageClassName: storageos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
